### ISSUE TITLE
jayのAPI Hookを実装する

### ISSUE THREAD

**Issue by ikeda-yuko** [nomlab/jay#44]
Created from [AI0022](http://jay.swlab.cs.okayama-u.ac.jp/minutes/158?ai=0022) of minute 158.
+ config/application_setting.ymlの階層を以下にする．
```
   incoming_webhooks:
       - strategy: GitHub    
         token: XXXXXXXX
   outgoing_webhooks:
       - url: http://XXXXXXXX
         content_type:
         events:
           - create
```
+ webhook_actionメソッドは，payloadの中身を単純にPOSTするだけにする．
+ requestのbodyを成形する部分はプライベートメソッドとし，各actionのメソッド内でそのメソッドを呼び出す．
+ 現状，前処理が必要な場面が想定できないため，webhook_action メソッドは around_action からafter_actionに変更する．
+ POSTに失敗し，rescueしたときに nil を返却するのではなく，エラーオブジェクトを返却する．
+ flash にはエラーオブジェクトのメッセージを表示する．
